name: Deploy to GitVerse Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.repository == 'klon_008/princtascdwk' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
        env:
          VITE_ALBUM_LINK_SECRET: ${{ secrets.ALBUM_LINK_SECRET }}

      - name: Upload pages artifact
        uses: gitverse/upload-pages-artifact@v1.0.0
        with:
          path: dist

  deploy:
    if: ${{ github.repository == 'klon_008/princtascdwk' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: gitverse/deploy-pages@v1.0.0
